### ISSUE TITLE
Mongo Explorer doesn't work

### ISSUE THREAD

**Issue by mikamikuh** [dboissier/mongo4idea#100]
I'm trying to use Mongo Explorer plugin on WebStorm, but it doesn't work. I added mongo executable pass and server's path from Preferences dialog. It shows the server, but it doesn't show the contents below the server. Why?

My environment is as follows:
* Mac OSX 10.9.5
* WebStorm 9.0.3
* MongoDB 2.6.6

**Comment by dboissier** [comment]
Hi,

Lastest version of Jetbrains products version has some internal changes and make the plugin crashes. I am on it and keep you inform when the bug is fixed.

Cheers,

David

**Comment by metasean** [comment]
I've been going through the BOSSABLE series on MEAN.js.  In the video for Day 14[1], Shristi shows how to load and start using Mongo Explorer.  When I couldn't get it to work, I found this issue report.  I'm on WebStorm 9, which was a recent upgrade, so I assume I'm running into the same problem.  

I'm really excited to try Mongo Explorer with WebStorm 9!  Any estimate on when Mongo Explorer might be upgraded?

[1] http://www.bossable.com/648/mean-mongo-angularjs-batarang/

**Comment by jadeye** [comment]
does for me...just installed it from the settings->plugins

**Comment by metasean** [comment]
@jadeye - Thanks for letting me know!  Since I had gotten the "Connection Successful!" message when configuring access and then didn't have access, which sounded like this bug, I didn't keep debugging on my end.  Turns out I had erroneously capitalized a letter in the configuration.  I wouldn't have gone back digging if it weren't for your comment.  So thank you!

**Comment by dboissier** [comment]
Hi,

I uploaded a [snapshot](https://github.com/dboissier/mongo4idea/raw/master/snapshot/mongo4idea-0.7.0-SNAPSHOT-Idea14-distribution.zip) version tested on Webstorm 9. It should work on Idea 14 too.

Please tell me if it works on your IDE.

David

**Comment by jadeye** [comment]
@metasean glad I could be of assistance :-)

**Comment by dboissier** [comment]
Hi @metasean and @jadeye,

Could you please confirm the [SNAPSHOT](https://github.com/dboissier/mongo4idea/raw/master/snapshot/mongo4idea-0.7.0-SNAPSHOT-Idea14-distribution.zip) plugin works on Webstorm 9?

Thanks

**Comment by jadeye** [comment]
Hi @dboissier - I was reffering to v0.6.1 on webstorm...I will give your snapshot a try.

**Comment by jadeye** [comment]
@dboissier - that didn't take long...working :+1:

**Comment by dboissier** [comment]
Great, official release will be available on the jetbrains plugin repository tomorrow.

Thanks

**Comment by jadeye** [comment]
:100:

**Comment by dboissier** [comment]
Release 0.7.0 available on Jetbrains plugin repository

**Comment by metasean** [comment]
@dboissier - I just installed 0.7.0 without any major hitches.

**Comment by vtechmonkey** [comment]
keeps crashing for me. Test connection works fine, but mongo explorer crashes as soon as I click on the icon or before. I get this error - 
4:07:49 MongoTimeoutException: Error when collecting Mongo databases: Timed out after 30000 ms while waiting for a server that matches ReadPreferenceServerSelector{readPreference=primary}. Client view of cluster state is {type=UNKNOWN, servers=[{address=mongolab.com:xxxxx, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.SocketTimeoutException: connect timed out}}]

**Comment by BlackBsd** [comment]
Hello all,
using Idea 2016.01 and this plugin seems to be timing out consistently.  I am trying to connect to a database using ssl and i am getting the following errors: 

Error when accessing Mongo server: Timed out after 30000 ms while waiting for a server that matches ReadPreferenceServerSelector{readPreference=primary}. Client view of cluster state is {type=UNKNOWN, servers=[{address=<My_Server>:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketWriteException: Exception sending message}, caused by {javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target}, caused by {sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target}, caused by {sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target}}]

Any Ideas?

**Comment by dboissier** [comment]
This is caused by Java 1.7. If you run it under Java 1.6, you should not get this message.

**Comment by BlackBsd** [comment]
I see, its my understanding that with Idea 16, or as its newly named 2016.1, the IDE will require java 8 to run under.

https://intellij-support.jetbrains.com/hc/en-us/articles/206544879-Selecting-the-JDK-version-the-IDE-will-run-under

**Comment by iraklisg** [comment]
I am having the same problem 

> Error when accessing Mongo server: Timed out after 30000 ms while waiting for a server that matches ReadPreferenceServerSelector{readPreference=primary}

@BlackBsd double clicking the newly added server didn't do the trick for me
