### ISSUE TITLE
Error connecting with WebStorm 11.01

### ISSUE THREAD

**Issue by bootylactin** [dboissier/mongo4idea#124]
Thanks for all your work on this plugin!  I recently upgraded to WebStorm 11.01 from version 10.  I am unable to install the 0.7.2 version of the Mongo plugin because of a version incompatibility error.  So I'm running 0.7.0.

Now when attempting to connect to a Mongo on the network, I receive the following error.  I have not changed the server configuration, and this used to work in WebStorm 10.x.

Error when collecting Mongo databases: Timed out after 10000 ms while waiting for a server that matches {serverSelectors=[ReadPreferenceServerSelector{readPreference=primary}, LatencyMinimizingServerSelector{acceptableLatencyDifference=15 ms}]}. Client view of cluster state is {type=ReplicaSet, servers=[{address=ip-10-220-4-47:27000, type=Unknown, state=Connecting, exception={com.mongodb.MongoException$Network: Exception opening the socket}, caused by {java.net.UnknownHostException: ip-10-220-4-47}}]

Note that I am able to connect to a Mongo server running on localhost.

Any ideas?  Thanks!

Jon

**Comment by dboissier** [comment]
Hi,

I made some changes in the way to connect to the Mongo server. How your server is configured?

Thanks,

David

**Comment by soulxy** [comment]
@dboissier 
Install this plugin(0.7.3) in my webstorm2016.1 , When I click test connection ,error ...

MongoTimeoutException: Error when accessing Mongo server: Timed out after 30000 ms while waiting for a server that matches ReadPreferenceServerSelector{readPreference=primary}. Client view of cluster state is {type=UNKNOWN, servers=[{address=localhost:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused: connect}}]

**Comment by soulxy** [comment]
sorry,I use mongodb first...
look document and find my question

**Comment by sarkistlt** [comment]
same issue, trying to connect db on mlab.com, MongoChef works fine with same configs

**Comment by dboissier** [comment]
Hi,

Do you still encounter this issue?
