### ISSUE TITLE
So... added a key, and all my collections vanished.

### ISSUE THREAD

**Issue by annitya** [dboissier/mongo4idea#167]
Just our dev-database, but slightly annoying nonetheless.

**Comment by dboissier** [comment]
Hi,

Could you please provide me the steps which engendered this issue?

Thanks

**Comment by whitefire** [comment]
Hi! 

Thanks for responding! :-)

It was late and I was tired, but I attempted to add a new key while editing a document. I suspect I might have clicked in the wrong spot. 

Upon saving the document, the window containing the document-list was replaced by the values of the saved document only. 

I attempted to retrieve the list again, but didn't succeed because all collections were gone.

**Comment by dboissier** [comment]
In the plugin, you can delete document only by right-clicking on the ObjectId. Same thing for collection (with a confirm step).

The truth might be out there ;)

**Comment by whitefire** [comment]
Might have been a freak Mongo-failure as well. No confirmations were had.

**Comment by dickreuter** [comment]
Same here, keep losing all database entries.
