### ISSUE TITLE
Cannot edit documents

### ISSUE THREAD

**Issue by initzx** [dboissier/mongo4idea#242]
I am unable edit the document values in the explorer. When i right-click on the field i wish to edit, the edit option is grayed out. What could be the cause for this problem?

**Comment by elbelife** [comment]
I have this problem too in IntelliJ IDEA ULTIMATE 2018.2.

**Comment by Orad** [comment]
Any way to bypass this ?

**Comment by fgm** [comment]
I had already tried the solution in #83 and it doesn't work. 

![image](https://user-images.githubusercontent.com/143311/48617301-5aa61480-e996-11e8-85ea-39525bdcfbd0.png)

Still applies in GoLand 2018.3 (GO-183.4284.84)

**Comment by danielkiedrowski** [comment]
Same

**Comment by d0m3n** [comment]
Same.

**Comment by turboSlowPoke** [comment]
Same

**Comment by fgm** [comment]
In the case for which I gave a screenshot earlier (2018-11-16), these are externally generated string ids. Essentially the string form of ObjectIDs, actually.

**Comment by cbm-dboissier** [comment]
The "classical" form the ObjectId value is hexadecimal char but I suppose the spec has changed and is more opened, right?

**Comment by fgm** [comment]
In this specific case, it is an encoded version, more compact, but it does not really matter: IMHO since essentially any scalar can be used for an _id, using the string representation of the _id, usable with ObjectID too, would provide a unified type for _id you could use in the plugin (since I guess it's Java and you need an actual type ?)

**Comment by cunneen** [comment]
@xstable , is the zip file above not working for you?

> I just submitted a pull request; the modified plugin can be downloaded below.
> 
> [mongo4idea.zip](https://github.com/dboissier/mongo4idea/files/2738989/mongo4idea.zip)
> 
> To use it, uninstall the official plugin and then install it from disk.
> 
> ![image](https://user-images.githubusercontent.com/1751645/50869732-3ee84900-13f0-11e9-9d2f-015e4f839ea1.png)

**Comment by xstable** [comment]
@cunneen didn't try it. If you still solved it, (like you did), would love to see that the team doing  the merge.
I prefer the general way to upgrade Plugins. 
As long as this merge is pending I start to use mongodb-compass.

**Comment by cbm-dboissier** [comment]
Dear @xstable, the team of this plugin is composed by me and myself. I build it few years ago for professional needs and I was happy to share it.
As you may know, OSS are maintained by people who have parse time and motivation, mostly unpaid.
I understand your frustration because this bug annoys you. The point is I do not have time to work on it because I am full both professional and personal. If you read the Apache License 2.0, this plugin is provided **as is**.

I would like to thank @cunneen for his PR and the build he shares to unblock the situation. I sorry for not having merging it for now. I hope I will have some time to make some serious enhancement.

Thanks.

**Comment by antonkomarev** [comment]
@cunneen I've tried it. Not still read-only mode.

**Comment by mattdavis1121** [comment]
@cunneen Installed from your .zip correctly, I believe. Still having the read-only issue.

**Comment by cunneen** [comment]
@mattdavis1121 and @antonkomarev , it works fine for me. You need to right-click on the ID (not on any other properties) in order to edit. See attached.

![mongo4idea](https://user-images.githubusercontent.com/1751645/56257647-82450880-60ff-11e9-9028-2c10e7173fb1.gif)

**Comment by xstable** [comment]
When will this fix be merged in the master?

**Comment by mattdavis1121** [comment]
> You need to right-click on the ID (not on any other properties) in order to edit. See attached.

This was the problem! I can't be the only one who was just using the tool wrong. The base install from this repo works, then. It just doesn't work how I thought it would.

**Comment by cunneen** [comment]
> The base install from this repo works, then. It just doesn't work how I thought it would. 

This just fixes an issue where the ID is not generated by MongoDB i.e. it's not an `ObjectId(...)`; the base install currently doesn't work for such documents.

Glad you figured it out.

**Comment by xstable** [comment]
For me, the content-window never opens:
PHPSTORM 2019.1.2
Mongo-Explorer: 0.12.2

![mongo_explorer](https://user-images.githubusercontent.com/1778068/58864498-246f7e80-86b5-11e9-9f39-90a93dccdcd8.gif)
